# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RightBrain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for RightBrain
pod "YYModel"
pod "FMDB"
pod "Masonry"
pod "SVProgressHUD"
pod "EZDrawer"
pod "MJRefresh"
pod 'pop', '~> 1.0'

end
